/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * panelPublicaciones.java
 *
 * Created on Apr 15, 2019, 2:20:12 AM
 */

package vistas;

import javax.swing.table.DefaultTableCellRenderer;

/**
 *
 * @author alvaro
 */
public class panelPublicaciones extends javax.swing.JPanel {

    /** Creates new form panelPublicaciones */
    public panelPublicaciones() {
        initComponents();
//       tblPub.setOpaque(false);
//       ((DefaultTableCellRenderer)tblPub.getDefaultRenderer(Object.class)).setOpaque(false);
//        jScrollPane1.setOpaque(false);
//        jScrollPane1.getViewport().setOpaque(false);

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setOpaque(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 520, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
