/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * plataforma.java
 *
 * Created on Apr 15, 2019, 3:02:26 AM
 */

package vistas;

import java.awt.Color;
import clases.pintarPanel;

/**
 *
 * @author alvaro
 */
public class plataforma extends javax.swing.JFrame {
pintarPanel pintor = new pintarPanel();
panelPublicaciones panel = new panelPublicaciones();
    /** Creates new form plataforma */
    public plataforma() {
        initComponents();
        this.setLocationRelativeTo(null);

       
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panelNav = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        lblnomb = new javax.swing.JLabel();
        lblPub = new javax.swing.JLabel();
        lblTrab = new javax.swing.JLabel();
        lblUsr = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        panelLateral = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        btnPerfil = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        panelNav.setBackground(new java.awt.Color(54, 54, 87));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Iconomenu2.png"))); // NOI18N
        jButton1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton1.setBorderPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        lblnomb.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        lblnomb.setForeground(java.awt.Color.white);
        lblnomb.setText("UMSS");

        lblPub.setForeground(java.awt.Color.white);
        lblPub.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPub.setText("Publicaciones");
        lblPub.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        lblPub.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblPub.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblPubMouseClicked(evt);
            }
        });

        lblTrab.setForeground(java.awt.Color.white);
        lblTrab.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTrab.setText("Trabajos");
        lblTrab.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        lblUsr.setForeground(java.awt.Color.white);
        lblUsr.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUsr.setText("Usarios");
        lblUsr.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jLabel5.setForeground(java.awt.Color.white);
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("jLabel5");
        jLabel5.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jLabel6.setForeground(java.awt.Color.white);
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("jLabel6");
        jLabel6.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        javax.swing.GroupLayout panelNavLayout = new javax.swing.GroupLayout(panelNav);
        panelNav.setLayout(panelNavLayout);
        panelNavLayout.setHorizontalGroup(
            panelNavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNavLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addGap(24, 24, 24)
                .addComponent(lblnomb, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(94, 94, 94)
                .addComponent(lblPub, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTrab, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblUsr, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelNavLayout.setVerticalGroup(
            panelNavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNavLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(panelNavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPub, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTrab, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUsr, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(panelNavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addGroup(panelNavLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(lblnomb))
                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelNavLayout.createSequentialGroup()
                    .addGap(33, 33, 33)
                    .addComponent(jButton1)))
        );

        getContentPane().add(panelNav, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 80));

        panelLateral.setBackground(new java.awt.Color(38, 119, 253));
        panelLateral.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/IconoUsuario.png"))); // NOI18N
        jButton2.setBorderPainted(false);
        panelLateral.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 32, 70, 70));

        btnPerfil.setText("Editar perfil");
        btnPerfil.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnPerfil.setBorderPainted(false);
        btnPerfil.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelLateral.add(btnPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 100, 30));

        btnEdit.setText("Modo Edicion");
        btnEdit.setBorderPainted(false);
        panelLateral.add(btnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 100, 30));

        jSeparator1.setBackground(java.awt.Color.white);
        panelLateral.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 150, 5));
        panelLateral.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 150, 5));

        getContentPane().add(panelLateral, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 150, 520));

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/FondoMenuDocente.jpg"))); // NOI18N
        getContentPane().add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int posicion = panelLateral.getX();
        if(posicion == 0){
            panelLateral.setLocation(-150, 80);
        }else{
            panelLateral.setLocation(0, 80);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void lblPubMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPubMouseClicked
            pintor.pintaPanel(this, panel);
    }//GEN-LAST:event_lblPubMouseClicked

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new plataforma().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnPerfil;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblPub;
    private javax.swing.JLabel lblTrab;
    private javax.swing.JLabel lblUsr;
    private javax.swing.JLabel lblnomb;
    private javax.swing.JPanel panelLateral;
    private javax.swing.JPanel panelNav;
    // End of variables declaration//GEN-END:variables

}
